from . import discount_tier
from . import res_partner
from . import product
from . import audit_log
from . import approval
from . import sale_order_line
from . import sale_order
from . import res_config_settings
from . import negotiation
from . import warehouse_split
from . import recurring
from . import upsell
